### ISSUE TITLE
TPM Exception: TPM Error - TPM_RC::RC_VER1

### ISSUE THREAD

**Issue by zongxuzhang** [Microsoft/ms-tpm-20-ref#109]
Hello.
I created a new Cpp project in visual studio. After I connected to TPM and created the Tpm2 instance, I encountered an error when I called the method of the Tpm2 instance, for example, the GetRandom method. The output was displayed as TPM Exception: TPM Error - TPM_RC::RC_VER1.
I would appreciate it very much if I could get your reply.

**Comment by bradlitterell** [comment]
Your question is far too ambiguous to answer.  It's not even clear what you mean by "Tpm2 Instance".  There is no `Tpm2` class defined in this codebase.
