### ISSUE TITLE
Linux build docs

### ISSUE THREAD

**Issue by bkgoodman** [Microsoft/ms-tpm-20-ref#111]
Readme for linux says: `Follows the common ./bootstrap && ./configure && make convention.`

But there is no `./bootstrap` file, nor does it say how to make it

**Comment by bradlitterell** [comment]
The build environment is rooted in the TPMCmd folder, so the file is here: 
https://github.com/microsoft/ms-tpm-20-ref/blob/main/TPMCmd/bootstrap
