### ISSUE TITLE
travis-ci configuration

### ISSUE THREAD

**Issue by flihp** [Microsoft/ms-tpm-20-ref#22]
The commits merged in #8 add the configuration required to build the simulator on a Linux platform. The microsoft github project however needs to be configured to build it for pull requests etc. Enabling this is not something I can do with a PR though. The owner of the project must login to travis-ci.org (this can be done using your github credentials) and enable the configuration. If you feel this is something worth doing I'm happy to help however I can.

**Comment by amarochk** [comment]
This is certainly absolutely must-have feature, especially since you've already properly configured everything! :) I've activated tracking of our repo in Travis-CI, and added a link to the build status into README.md. It just works! Thank you once again, Philip!
