### ISSUE TITLE
SMX support

### ISSUE THREAD

**Issue by flihp** [Microsoft/ms-tpm-20-ref#27]
OpenSSL added support for SM2, 3 and 4 in the latest 1.1.1 release. Are there any plans to support these in the simulator?

**Comment by amarochk** [comment]
Hi Philip,

This is a question for the TPM WG in TCG. Adding SM support is generally a good idea, it is just that the reference implementation does not quite support 1.1 yet (because it has made private some of the definitions that used to be public in earlier versions).

**Comment by flihp** [comment]
Thx @amarochk. I'll do some digging around to see if I can find someone from that working group willing to share.
