### ISSUE TITLE
Reduce usage of Header textual inclusion

### ISSUE THREAD

**Issue by josephlr** [microsoft/ms-tpm-20-ref#33]
Some C/C++ systems (like [Bazel](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library)) can optimize C/C++ builds using the fact that most headers don't have content that changes based on _how_ it is included in a file. They can then use [precompiled headers](https://en.wikipedia.org/wiki/Precompiled_header) or more advanced methods to speed up building.

However, `libtpm` makes frequent use of a pattern where the symbols defined _before_ including a header significantly change it's content. This makes this optimization impossible for a good deal of the library making building slower than it needs to be.

Most of the uses can be easily eliminated. The only one that would be tricky is `Global.h`, which nicely avoids duplication between `Global.h` and `Global.c`.

**Comment by amarochk** [comment]
Hi Joseph,

Thank you for your analysis and suggestions. The speed of the compilation has never really been a consideration of the TPM reference implementation design. One of the primary goals on the current period of its life cycle is preserving its stability. Thus any non-trivail changes are normally only made to fix logical errors, meaningfully optimize performance or space efficiency, or add new functionality. Please keep this in mind when suggesting changes.

If you want to further discuss your ideas with a broader audience, you are welcome to join the TPM Work Group in the TCG (Trusted Computing Group consortium). It should be easy for you, as your company is already a TCG member.

Thanks,
-Andrey Marochko
