### ISSUE TITLE
Driver not loaded

### ISSUE THREAD

**Issue by vivinamartins16** [microsoft/ms-tpm-20-ref#37]
Hey all!

I'm building fTPM with OP-TEE on Qemu. Following the instructions, I got to build the solution but the driver didn't load. I got the following on my Normal World shell:

```
Starting tee-supplicant: OK
Starting network: OK
Starting network (udhcpc): OK
Starting tpm2-abrmd: device driver not loaded, skipping.
```

What am I missing?

p.s: I see no evidence of the TA being loaded in the secure world.

Thanks in advance!

**Comment by amarochk** [comment]
I believe the active support of the fTPM TA has migrated to the (MSRSec)[https://github.com/microsoft/MSRSec] repo.
