### ISSUE TITLE
64bit builds & Linux

### ISSUE THREAD

**Issue by flihp** [Microsoft/ms-tpm-20-ref#4]
I've been working up a few patches to enable use of this code on Linux. Currently I have done enough to get a functional daemon running with test cases from https://github.com/tpm2-software/tpm2-tss.git working as expected. I'm only able to do so when building for a 32bit host though. 64bit builds produce a binary just fine but it hangs when handling commands and I wanted to check to see if 64bit builds are intended to work at all before I spend time debugging this.

My intention is to submit this work as a PR once I've cleaned it up a bit and sorted out this issue with the 64bit builds.

Thanks.

**Comment by amarochk** [comment]
Hi Philip,

Yes, it would be great if the 64-bit version worked too. But if it going to take significant time, you could commit your 32-bit-only version first.

Thanks,
-Andrey

**Comment by amarochk** [comment]
64-bit build works fine as long as you give it the correct (64-bit) OpenSSL binaries (and matching headers). You'll only need to update the '#define RADIX_BITS' definition in Implementation.h (you'll get a compile time error if it does not match the underlying crypto library requirements).

**Comment by flihp** [comment]
Thanks for the hint here @amarochk. This helped a lot in debugging a gap in the RADIX_BITS sanity checks that are done in `TPMCmd/tpm/include/ossl/TpmToOsslMath.h`. Just put up a PR to fill this gap: #6
