### ISSUE TITLE
Incorrect filename case in folder structure.

### ISSUE THREAD

**Issue by BradL-Msft** [microsoft/ms-tpm-20-ref#40]
Cloning with Git for Windows generates a warning about the case of filenames.  As a result, there is only one simulator.vcxproj on Windows, but two on Linux, and it's not obvious that the clone results are actually correct.

>git clone  https://github.com/microsoft/ms-tpm-20-ref.git
Cloning into 'ms-tpm-20-ref'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 4465 (delta 9), reused 17 (delta 9), pack-reused 4433R
Receiving objects: 100% (4465/4465), 6.36 MiB | 25.32 MiB/s, done.
Resolving deltas: 100% (3422/3422), done.
Checking out files: 100% (771/771), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'TPMCmd/Simulator/simulator.vcxproj'
  'TPMCmd/simulator/simulator.vcxproj'

**Comment by amarochk** [comment]
Thanks, Brad. 'TPMCmd/simulator/simulator.vcxproj' copy was introduced by mistake, and I've removed it.
