### ISSUE TITLE
There are two copies of Tpm.vcxproj.filters that differ only by case

### ISSUE THREAD

**Issue by neilsh-msft** [microsoft/ms-tpm-20-ref#41]
There are two copies of TPM.vcxproj.filters under TPMCmd/tpm that differ only by the case of the filename:

TPM.vcxproj.filters 
Tpm.vcxproj.filters

This causes issues for people who have cloned the repo into a non-case-sensitive file system.  Git will always say the file has been modified and will not let you switch branches.  One of them needs to be removed.

**Comment by amarochk** [comment]
Thanks, Neil! Looks like it's come along with the previous duplicate project file. I've removed it.
