### ISSUE TITLE
Question about manufacturer's endorsement key

### ISSUE THREAD

**Issue by kwtj43** [microsoft/ms-tpm-20-ref#47]
My understanding is that (when started) the tpm-simulator does not have a manufacturer's endorsement key.  This is a problem for me in that I can't simulate hardware devices (ex. Infineon TPM2) where the EK is present at nvindex 0x1c00002.

Are there any instructions on how to use openssl and tpm2-tools (tss) to prepare the tpm-simulator with a manufacture's endorsement key?  The only thing I have found is at https://google.github.io/tpm-js/#pg_certificates.

**Comment by mrcdb** [comment]
Hi Kent,

You may try this simple bash tool I wrote (extended actually) to generate and load an EK certificate in a TPM 2.0 simulator.

 https://github.com/mrcdb/tpm2_ek_cert_generator <https://github.com/mrcdb/tpm2_ek_cert_generator>

It has been tested with MS TPM2.0 sim some time ago, but I have not had a chance to try it lately. I hope it works for you.

**Comment by kwtj43** [comment]
Thanks Marco.  Your script has given me a path forward so this issue can be closed.

Thanks again for the quick response.
