### ISSUE TITLE
Uninitialised variable warning/error for "nvHandle" with GCC 10

### ISSUE THREAD

**Issue by diabonas** [microsoft/ms-tpm-20-ref#48]
When building with GCC 10, compilation fails with the following (fatal, due to `-Werror`) warning:
```
tpm/src/subsystem/NvDynamic.c: In function ‘NvNextByType’:
tpm/src/subsystem/NvDynamic.c:148:17: error: ‘nvHandle’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  148 |         *handle = nvHandle;
      |         ~~~~~~~~^~~~~~~~~~
cc1: all warnings being treated as errors
```
This might be a false positive and is probably easily fixed by initialising `nvHandle` [in l. 138](https://github.com/microsoft/ms-tpm-20-ref/blob/69437ff7622a0110ac2088fca5ae9bb265c0fb1c/TPMCmd/tpm/src/subsystem/NvDynamic.c#L138), but I am not sure what a safe initial value for doing so would be.

**Comment by amarochk** [comment]
Hi Jonas,

Thank you for submitting the issue. The local var initialization is indeed missing here, though the contexts that currently call this function never use the result of an uninitialized value assignment. We'll fix the code.

-Andrey
