### ISSUE TITLE
error: use of undeclared identifier 'tpmHashStateImport_SHA512'

### ISSUE THREAD

**Issue by xiaoyuxlu** [microsoft/ms-tpm-20-ref#65]
I try to enable `ALG_SHA512`, but I got compile error.

```
error: use of undeclared identifier 'tpmHashStateImport_SHA512'
```

Could you see if this definition is correct? Thanks. 

https://github.com/microsoft/ms-tpm-20-ref/blob/e3c585d7113bae31924d6fd483e65a166a32098f/TPMCmd/tpm/include/Ossl/TpmToOsslHash.h#L195

**Comment by jyao1** [comment]
It seems the `#define tpmHashStateImport_SHA_512  memcpy` should be `#define tpmHashStateImport_SHA512  memcpy`.

**Comment by jyao1** [comment]
This issue is fixed now.
