### ISSUE TITLE
CLA clarification

### ISSUE THREAD

**Issue by flihp** [Microsoft/ms-tpm-20-ref#7]
I've just noticed that the PRs I've created have an automated check performed: "license/cla — All CLA requirements met." There's a link in this text to `https://msght/` but attempts to follow this link result in an error: `ERR_CONNECTION_REFUSED`.

Can you provide details on what the CLA is?

**Comment by amarochk** [comment]
I suppose it must be this: https://cla.opensource.microsoft.com/

**Comment by flihp** [comment]
I guess that covers what the CLA is. Now how does it relate to this project?

**Comment by flihp** [comment]
I took a look at the link you provided again and the relevant part seems to be:
```
When you contribute to a Microsoft open source project on GitHub with a new pull request, a bot will evaluate whether you have signed the CLA. If required, the bot will comment on the pull request, including a link to this system to accept the agreement.
```
Since I never signed the CLA and the bot didn't comment on my PRs then I take that to mean that signing the CLA isn't required for this project. If this is correct please just close this issue and I'll just keep sending PRs.

Thanks again for the clarification @amarochk. Apologies for the confusion.

**Comment by amarochk** [comment]
Yes, most probably this is it, and this is why your link was invalid. This project (and many other Microsoft projects) had passed an internal release approval procedure before it was published under a standard open-source license (BSD License in our case), and this license is supposed to cover all aspects of its life cycle from then on.
