### ISSUE TITLE
Is the generator for the TPM sources available?

### ISSUE THREAD

**Issue by sharadhr** [microsoft/ms-tpm-20-ref#79]
The TPM sources used by all the samples, and especially the simulator in TPMCmd, have these [telltale lines](https://github.com/microsoft/ms-tpm-20-ref/blob/5c7941b246c2d38d75c3d91d36e1b792374019f1/TPMCmd/tpm/include/TpmTypes.h#L35):

>     /*(Auto-generated)
>      *  Created by TpmStructures; Version 4.4 Mar 26, 2019
>      *  Date: Mar  6, 2020  Time: 01:50:09PM
>      */

Is the source for this `TpmStructures` script/binary available? I presume based on [this discussion](https://github.com/microsoft/ms-tpm-20-ref/pull/52#pullrequestreview-594878305) that the generator parses the TPM 2.0 specification itself to generate code. 

Equivalent work is in [TSS.MSR/TssCodeGen](https://github.com/microsoft/TSS.MSR/tree/master/TssCodeGen), but that doesn't seem to generate C source code (like is seen in this repository), but rather equivalent structures in higher-level languages. 

[TpmScripts](https://github.com/DavidWooten/TpmScripts) seems likely, but the repository is empty; there are references to it in [this repository's gitignore](https://github.com/microsoft/ms-tpm-20-ref/blob/5c7941b246c2d38d75c3d91d36e1b792374019f1/.gitignore#L336), too.

**Comment by bradlitterell** [comment]
Sorry, at the current time, those tools are not available publicly.

**Comment by DemiMarie** [comment]
@bradlitterell could they be replaced by TssCodeGen?

**Comment by bradlitterell** [comment]
No TssCodeGen generates TPM client code. Your original request was, I believe, for the TPM implementation code, which is a different tool.

________________________________

**Comment by bradlitterell** [comment]
Not currently, no.  Sorry.

**Comment by DemiMarie** [comment]
> Not currently, no. Sorry.

Understood.  Can you provide the reason, or is that also confidential?

**Comment by bradlitterell** [comment]
> > Not currently, no. Sorry.
> 
> Understood. Can you provide the reason, or is that also confidential?

Simple practicality.  They are complex and troublesome, and we wouldn't have the bandwidth to explain or support them for arbitrary users.  Plus, we have plans to remove them entirely.

**Comment by DemiMarie** [comment]
> > > Not currently, no. Sorry.
> > 
> > 
> > Understood. Can you provide the reason, or is that also confidential?
> 
> Simple practicality. They are complex and troublesome, and we wouldn't have the bandwidth to explain or support them for arbitrary users. Plus, we have plans to remove them entirely.

Will the replacement be publicly available?  I ask because there are changes (like #104) that can only be made in the code generator.
