### ISSUE TITLE
fTPM usage of RTC

### ISSUE THREAD

**Issue by railabouni** [microsoft/ms-tpm-20-ref#80]
hi all,

My question is if fTPM needs a secure real time clock for it to be able to work? 

Thank you!

**Comment by bradlitterell** [comment]
Apologies for not answering.  In case you haven't answered the question already, see Part 1 of the TPM 2.0.  Section 36 describes the timing components required by a TPM.
The short answer is: 
* secure real time clock, no.  
* internal millisecond timer _while powered on_, yes.

**Comment by railabouni** [comment]
thank you Brad :)
