### ISSUE TITLE
Info on Microsoft CLA missing from CHANGELOG.md

### ISSUE THREAD

**Issue by flihp** [Microsoft/ms-tpm-20-ref#9]
PR #8 is currently blocked by the Microsoft CLA bot. This conflicts with data in #7. Would it be possible to get info on CLA requirements in your documentation for contributors / contributions (aka CONTRIBUTING.md). This will help contributors like myself in planning since I need approval from my employer before I contribute to projects and a CLA is like a 10x multiplier on the complexity of this process. Knowing this in advance will save us a lot of time.

**Comment by amarochk** [comment]
Honestly, until you mentioned it, I had not had any idea about this CLA. Probably it's a new "feature" added after the recent GitHub acquisition by Microsoft...

**Comment by amarochk** [comment]
@RonaldAi has updated CONTRIBUTING.md - thanks, Ron! Evidently MSFT has always required contributors to its projects to sign this CLA (once), if the contribution size exceeded some limit.
